export const DEPENDENCY_CLIENTS_ID = 'NK0caSsNdziSo64RKhGUuv7Ev&Bn';
export const DEPENDENCY_SUPPLIERS_ID = 'lcCuXfAev7UJtHr7eQDbYh7ldN7K';
export const DIRECTED_RELATIONSHIP_SOURCES_ID = '_FHdhz9m77&6D0ezEAIz1wTHosuY';
export const DIRECTED_RELATIONSHIP_TARGETS_ID = 'y3jO9&br6vLo7t50PMinNTMu4wHv';
export const ELEMENT_APPLIED_STEREOTYPES_ID = 'GGrJHpnxeSMB14vyGKEhbbwa6iCR';
export const ELEMENT_OWNED_COMMENTS_ID = 'd8boa7uurAj2JNoQMbCe69k89d1M';
export const ELEMENT_OWNED_ELEMENTS_ID = 'XtmmRpH294S3m9x9Bp8FT63LuCMl';
export const ELEMENT_OWNER_ID = 'XIKAlIqrt4NOzZBgAKzoXuLIH2DS';
export const NAMED_ELEMENT_CLIENT_DEPENDENCIES_ID = 'KDgwtlUDTBZuGIAAed8D5blGk98f';
export const NAMED_ELEMENT_NAMESPACE_ID = 'XjBtcuD1gdltfGHP3NqzlXg61zbh';
export const NAMESPACE_MEMBERS_ID = 'ypBZodwaaRcE7gld4WuSbrsav39p';
export const NAMESPACE_OWNED_MEMBERS_ID = 'RFhcUcft&ayqEN8IOPI1ftyO5gsx';
export const PACKAGEABLE_ELEMENT_OWNING_PACKAGE_ID = 'PL0LXBVcYZKI2s3zYLO4d_2R9_tV';
export const PACKAGE_PACKAGED_ELEMENTS_ID = 'F628ncQKADxo6FLtAlDOdlJfewLy';
export const RELATIONSHIP_RELATED_ELEMENTS_ID = 'EZZ0a&j9jg_PEmjwEJvkTYzfAuKl';

