export const ABSTRACTION_ID = '';
export const ASSOCIATION_ID = 'thwOzkNWxyNS173nicaNAgtMOxdT';
export const ASSOCIATION_MEMBER_ENDS_ID = 'd8zBcyATDRBFGVmH5iDnhcPK75Az';
export const ASSOCIATION_NAVIGABLE_OWNED_ENDS_ID = '5C0yj0wfSbiWvILuj8OS68-CqLJE';
export const ASSOCIATION_OWNED_ENDS_ID = 'JlEgzt8KZtjezaH4EOmSR8Va1uJz';
export const CLASS_ID = 'qyMDE1FPSey_RdXCjwifMXS70MiF';
export const CLASS_OWNED_ATTRIBUTES_ID = 'N0AP6gsEA_lVyI3CsenzzBChuZ0x';
export const CLASSIFIER_ID = '13wa8TtmphWD1reWGwNUhyS0Rk9y';
export const CLASSIFIER_GENERALIZATIONS_ID = 'xgmvbUmIrJ9jZG-HKOw0tOKhN9eS';
export const CLASSIFIER_FEATURES_ID = '5pvS7Q1wlyZbihnK1eqOnOMLgLS-';
export const CLASSIFIER_ATTRIBUTES_ID = 'qFjM5899B6bmuxuplcin9csEUa_g';
export const COMMENT_ID = 'zltysmxidp1ci2PhAz9mrG_GgVna';
export const COMMENT_ANNOTATED_ELEMENTS_ID = 'LZ2gyp2q4IVggFXMhkbNe1bp24FI';
export const CONNECTABLE_ELEMENT_ID = 'GbrzuIyDPnXa86lVHBgbWGUKYfaE';
export const DATATYPE_ID = 'taZDRFlyHumZS94qEHGMIXWDi-pE';
export const DATATYPE_OWNED_ATTRIBUTES_ID = 'YRfW6j4vEoAIs5IZxAhzL-Xrfi4E';
export const DEPENDENCY_ID = 'SPwEe86n-OnH2AJBALFk7qNGzOLd';
export const DEPENDENCY_CLIENTS_ID = 'NK0caSsNdziSo64RKhGUuv7Ev-Bn';
export const DEPENDENCY_SUPPLIERS_ID = 'lcCuXfAev7UJtHr7eQDbYh7ldN7K';
export const DIRECTED_RELATIONSHIP_ID = '6GWi2oAkBrSYm1ZjpmJprB_Fhirv';
export const DIRECTED_RELATIONSHIP_SOURCES_ID = '_FHdhz9m77-6D0ezEAIz1wTHosuY';
export const DIRECTED_RELATIONSHIP_TARGETS_ID = 'y3jO9-br6vLo7t50PMinNTMu4wHv';
export const ELEMENT_ID = 'XI35viryLd5YduwnSbWpxSs3npcu';
export const ELEMENT_APPLIED_STEREOTYPES_ID = 'GGrJHpnxeSMB14vyGKEhbbwa6iCR';
export const ELEMENT_OWNED_COMMENTS_ID = 'd8boa7uurAj2JNoQMbCe69k89d1M';
export const ELEMENT_OWNED_ELEMENTS_ID = 'XtmmRpH294S3m9x9Bp8FT63LuCMl';
export const ELEMENT_OWNER_ID = 'XIKAlIqrt4NOzZBgAKzoXuLIH2DS';
export const ENCAPSULATED_CLASSIFIER_ID = 'E1UQWIIkowAMd5v62ARHi2cEvbDR';
export const ENUMERATION_ID = 'C4f1r16PLhBqvIYXPyqcs22lQZUw';
export const ENUMERATION_OWNED_LITERALS_ID = '0bbShzyDGBoiPzK0yL7mlNf74vTb';
export const ENUMERATION_LITERAL_ID = '31iTIAGgHNByNnW0zvxM5AwXxsAl';
export const ENUMERATION_LITERAL_ENUMERATION_ID = 'VL8ZmpG7YGf8VqW_H44oqD_R5Zll';
export const EXTENSION_ID = 'hDFC8hvr-D7CQLrTE8tvipQ7tz_8';
export const EXTENSION_OWNED_END_ID = 'igEp5i15i4BoE-2swNhF6w84BF-I';
export const EXTENSION_END_ID = 'O_7HEQc9Z9tCgUGdg51Y8sMf64MG';
export const FEATURE_ID = 'P26npn-Eihvfc8wmGIJzB4XMbXDl';
export const FEATURE_FEATURING_CLASSIFIER_ID = 'YrJ4n1R3EqvXEESg4y6KMeakK2EL';
export const GENERALIZATION_ID = 'uprxxN9V5lyTmO3X4MxPjYU1LBLU';
export const GENERALIZATION_GENERAL_ID = 'wEgOiXpA9Tw-JquWlj4qO3-cWot9';
export const GENERALIZATION_SPECIFIC_ID = 'jT-SRPuPxWJ0bJic11xKhaM87ghd';
export const INSTANCE_SPECIFICATION_ID = '3jGx_iRKqVpRXsyRTC7Kddvjs1iB';
export const INSTANCE_SPECIFICATION_CLASSIFIERS_ID = 'YpZ9-oJJ6ovW5-6If5lTmik-RQQj';
export const INSTANCE_SPECIFICATION_SLOTS_ID = 'PKeMhq71InnxiqcJgmoWNe0Kl-1N';
export const INSTANCE_SPECIFICATION_SPECIFICATION_ID = 'bRYJdS3KkJwyt9oSd_NV4FFhIfKE';
export const INSTANCE_VALUE_ID = '82o7Q_hCNaAWLHKhDoFKpR6reyeu';
export const INSTANCE_VALUE_INSTANCE_ID = 'PS7IdeknPVzfxqJ8OTgQzohKd7Rl';
export const LITERAL_BOOL_ID = '7ixjcT51wpUzjtmV-oc93icC1X1w';
export const LITERAL_INT_ID = 'wI3M3uikz0z6QHpVNIJrta1ROmQc';
export const LITERAL_NULL_ID = 'd_rlIDJLRy1o061SE8A0WU1mSm2R';
export const LITERAL_REAL_ID = 'ZHCpZ-iaDFbAF8_vU1_epYPWVGbq';
export const LITERAL_SPECIFICATION_ID = 'wGvs2ha18hTJkgUJjn0QqIjtnmR3';
export const LITERAL_STRING_ID = '7MtxvK9LN2LFLvG5y6zxPPCuwZYC';
export const LITERAL_UNLIMITED_NATURAL_ID = 'I7xHkZlJjKY1nnldgTKowujN3UDq';
export const MULTIPLICITY_ELEMENT_ID = '2MX9sVvjWDKkGFCl6jSEYTeJfCgn';
export const MULTIPLICITY_ELEMENT_LOWER_VALUE_ID = 'Iwnqqcp1OKg3dYryp9Ckoagw_44c';
export const MULTIPLICITY_ELEMENT_UPPER_VALUE_ID = 'Cfl8pdxVKDi27IekVEmJ6gyRLmXD';
export const NAMED_ELEMENT_ID = 'Ox30_bFSsGtPZorPYOkDTLeXquIN';
export const NAMED_ELEMENT_CLIENT_DEPENDENCIES_ID = 'KDgwtlUDTBZuGIAAed8D5blGk98f';
export const NAMED_ELEMENT_NAMESPACE_ID = 'XjBtcuD1gdltfGHP3NqzlXg61zbh';
export const NAMESPACE_ID = 'pUg_kaODi6D0KMi6MXAJcMWMG3G_';
export const NAMESPACE_MEMBERS_ID = 'ypBZodwaaRcE7gld4WuSbrsav39p';
export const NAMESPACE_OWNED_MEMBERS_ID = 'RFhcUcft-ayqEN8IOPI1ftyO5gsx';
export const PACKAGEABLE_ELEMENT_ID = '-ve0WKXZ2Hn47xMl-Dl-lXPTMHD9';
export const PACKAGEABLE_ELEMENT_OWNING_PACKAGE_ID = 'PL0LXBVcYZKI2s3zYLO4d_2R9_tV';
export const PACKAGE_ID = 'zvAhfu-WNCI1cNXd3BkqhxywHAYY';
export const PACKAGE_PACKAGED_ELEMENTS_ID = 'F628ncQKADxo6FLtAlDOdlJfewLy';
export const PACKAGE_OWNED_STEREOTYPES_ID = 'f3emF_P7lUQCj92wICwZqIVIcw9E';
export const PARAMETERABLE_ELEMENT_ID = 'SCmsyxfK3rkeBWVbS0iMxZ4nykK8';
export const PRIMITIVE_TYPE_ID = '20NUBfbj9jj4c3qH8Af2K0lZnbN4';
export const PROFILE_ID = 'SDtG5vVuoYtsaMKtqM-CcWxaXEKY';
export const PROPERTY_ID = '9On4aqWFEGwEw6rway7E_8_spRrc';
export const PROPERTY_ASSOCIATION_ID = 'gCWcKwE5Kw2AKY5znPDleBTp_Nid';
export const PROPERTY_CLASS_ID = '1p269YwWkH9HxehdVjQ9NBL_YVvR';
export const PROPERTY_DATATYPE_ID = '1QgH6QgvtOGBrDU6WQy-UY9sQZ_4';
export const PROPERTY_DEFAULT_VALUE_ID = 'pQ_GGmgHjaCJJWVEUPGaqJm938m9';
export const PROPERTY_OWNING_ASSOCIATION_ID = '2WwfKSv8p8cxwJNjCsUReaBSVvJJ';
export const PROPERTY_SUBSETTED_PROPERTIES_ID = 'cWJ3pzQMLpI56xhvmb33j--1V_39';
export const PROPERTY_REDEFINED_PROPERTIES_ID = 'wD9hC3sTeNAcNyGh3RnW7SWIImL4';
export const REALIZATION_ID = '';
export const REDEFINABLE_ELEMENT_ID = 'yrjlltCbvz7t4VVSLU5d3cKO41Va';
export const REDEFINABLE_ELEMENT_REDEFINED_ELEMENTS_ID = 'Z-YvjYeWesI-xJ_j5vHwiAtvZD_f';
export const REDEFINABLE_ELEMENT_REDEFINITION_CONTEXT_ID = 'kcSfJsip-b8_Eg2UWxLwb0MaR4sP';
export const RELATIONSHIP_ID = 'QUowokvKRwjZYrwmci655pJh1OeW';
export const RELATIONSHIP_RELATED_ELEMENTS_ID = 'EZZ0a-j9jg_PEmjwEJvkTYzfAuKl';
export const SLOT_ID = 'J2fEvc8IAzFjpPZqvms_gccefSfy';
export const SLOT_DEFINING_FEATURE_ID = '4Z6EqaCMszp8Jm3pfJdLvLGpQaCY';
export const SLOT_OWNING_INSTANCE_ID = 'M_u0KJZqq2ol7Qo4ewruqV2B_vcp';
export const SLOT_VALUES_ID = 'jT301V4UEMD76BrZ7HPK9r3SaWhI';
export const STEREOTYPE_ID = '0XAr-hQb_xP_SNVNuo6Wybk7DY2y';
export const STEREOTYPE_PROFILE_ID = '2bqeQwbxvqiPN5EguSWTmLhFHc8s';
export const STRUCTURAL_FEATURE_ID = 'bkUfoeGEZRF52nRUXqshHTpVqFmX';
export const STRUCTURED_CLASSIFIER_ID = '5nN3bNaJ9L8Z1ArCUolvqnyTO0jY';
export const STRUCTURED_CLASSIFIER_OWNED_ATTRIBUTES_ID = 'WrQFN_WEBkkbwBshG76_qGRsh0Lm';
export const STRUCTURED_CLASSIFIER_PARTS_ID = 'kD2EJ5rI0ejL7W1npwzC373Ws1ys';
export const STRUCTURED_CLASSIFIER_ROLES_ID = 'k6BecMare3f49MVVcdCxtjU-EkN1';
export const TYPE_ID = 'G9SsXu7xbMEGASAD0WV8izcwtBap';
export const TYPED_ELEMENT_ID = 'Lv5Oi488I7QTIk0BDJMxK4ckAf4R';
export const TYPED_ELEMENT_TYPE_ID = 'Uxf3ayap8ZKqATyFZDo2ImJqDW1F';
export const USAGE_ID = '';
export const VALUE_SPECIFICATION_ID = 'Qn4wyzpcn06v3cpAbR1QPvSqYrZ_';

export const KERNEL_TYPES = new Set([
    ASSOCIATION_ID, 
    CLASS_ID, 
    CLASSIFIER_ID, 
    COMMENT_ID, 
    CONNECTABLE_ELEMENT_ID, 
    DATATYPE_ID,
    DEPENDENCY_ID,
    DIRECTED_RELATIONSHIP_ID,
    ELEMENT_ID,
    ENCAPSULATED_CLASSIFIER_ID,
    ENUMERATION_ID,
    ENUMERATION_LITERAL_ID,
    EXTENSION_ID,
    EXTENSION_END_ID,
    FEATURE_ID,
    GENERALIZATION_ID,
    INSTANCE_SPECIFICATION_ID,
    INSTANCE_VALUE_ID,
    LITERAL_BOOL_ID,
    LITERAL_INT_ID,
    LITERAL_NULL_ID,
    LITERAL_REAL_ID,
    MULTIPLICITY_ELEMENT_ID,
    NAMED_ELEMENT_ID,
    NAMESPACE_ID,
    PACKAGEABLE_ELEMENT_ID,
    PACKAGE_ID,
    PARAMETERABLE_ELEMENT_ID,
    PRIMITIVE_TYPE_ID,
    PROFILE_ID,
    PROPERTY_ID,
    REALIZATION_ID,
    REDEFINABLE_ELEMENT_ID,
    RELATIONSHIP_ID,
    SLOT_ID,
    STEREOTYPE_ID,
    TYPE_ID,
    TYPED_ELEMENT_ID,
    VALUE_SPECIFICATION_ID
]);
